/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:f923ab14-a6aa-4792-8a21-71b5532896f1",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_JFo5xm09s",
    "aws_user_pools_web_client_id": "7jjflvgosd7a18ipkph1ho8epm",
    "oauth": {}
};


export default awsmobile;
